### ISSUE TITLE
openssl/ssl.h': No such file or directory

### ISSUE THREAD

**Issue by pvenkatesan83** [drbild/sslpsk#21]
Hi,
  please help me.
I have try install sslpsk module in python i got below error. I have installed visual sudio 15 and openssl on my  windows pc.

------------------------e/sslpsk-1.0.0.tar.gz
Installing collected packages: sslpsk
  Running setup.py install for sslpsk ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\uic68729\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\uic68729\\AppData\\Local\\Temp\\pip-install-dqbz47lu\\sslpsk\\setup.py'"'"'; __file__='"'"'C:\\Users\\uic68729\\AppData\\Local\\Temp\\pip-install-dqbz47lu\\sslpsk\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\uic68729\AppData\Local\Temp\pip-record-n2l2413k\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\uic68729\AppData\Local\Temp\pip-install-dqbz47lu\sslpsk\
    Complete output (21 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\sslpsk
    copying sslpsk\sslpsk.py -> build\lib.win-amd64-3.8\sslpsk
    copying sslpsk\__init__.py -> build\lib.win-amd64-3.8\sslpsk
    creating build\lib.win-amd64-3.8\sslpsk\test
    copying sslpsk\test\test_sslpsk.py -> build\lib.win-amd64-3.8\sslpsk\test
    copying sslpsk\test\__init__.py -> build\lib.win-amd64-3.8\sslpsk\test
    copying sslpsk\test\__main__.py -> build\lib.win-amd64-3.8\sslpsk\test
    running build_ext
    building 'sslpsk._sslpsk' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\sslpsk
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\uic68729\appdata\local\programs\python\python38\include -Ic:\users\uic68729\appdata\local\programs\python\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsslpsk/_sslpsk.c /Fobuild\temp.win-amd64-3.8\Release\sslpsk/_sslpsk.obj
    _sslpsk.c
    sslpsk/_sslpsk.c(19): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\uic68729\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\uic68729\\AppData\\Local\\Temp\\pip-install-dqbz47lu\\sslpsk\\setup.py'"'"'; __file__='"'"'C:\\Users\\uic68729\\AppData\\Local\\Temp\\pip-install-dqbz47lu\\sslpsk\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\uic68729\AppData\Local\Temp\pip-record-n2l2413k\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by riaano** [comment]
You just need the following modules to be able to install correclty

Redhat/Centos: 
yum install openssl-devel

Debian:
apt install libssl-dev
