### ISSUE TITLE
setting specific PSK cipher to use on client side.

### ISSUE THREAD

**Issue by il023109** [drbild/sslpsk#3]
How could I set a specific cipher suite to use in client side.

It seems by default, the Cipher list in clientHello message are all cert based. so the connection will be refused by server side which expect PSK cipher suite.

**Comment by drbild** [comment]
Just specify the cipher string, same as the standard `ssl` lib:

    sslpsk.wrap_socket(sock, psk="mypsk",
                       ciphers="PSK-AES256-GCM-SHA384:PSK-AES256-CBC-SHA")

**Comment by drbild** [comment]
Only cipher suites supported by the underlying installation of openssl will be supported though.

**Comment by il023109** [comment]
Thanks.

What version of openssl came with the two DLLs from sslpsk?
Or maybe openssl is part of Python 3.6 that I am using?

**Comment by drbild** [comment]
It is `openssl-1.0.2k`. You can see all the versions in `appveyor.yml`.
