### ISSUE TITLE
how should key be specified

### ISSUE THREAD

**Issue by il023109** [drbild/sslpsk#4]
What if the key is not a string but 4 bytes of data, like 0x12345678

How can I specify the key in client side.

PSKS = {'server1' : '1234',
        'server2' : '0x1a2b3c4d'}

**Comment by drbild** [comment]
Just use standard Python binary strings:
```python
PSKS = {'server1': 'mystring',
        'server2': b'\x1a\x2b\3cx\4d'}
```

**Comment by il023109** [comment]
perfect, it works fine with my embedded server side now.

Thanks, great testing tool!

**Comment by drbild** [comment]
You're welcome!
